### ISSUE TITLE
无法启用插件

### ISSUE THREAD

**Issue by aiyunyuner** [immortalwrt/luci-app-unblockneteasemusic#55]
/usr/share/unblockneteasemusic/core/src/provider/match.js:54
			song.md5 = response.headers['etag'].replace(/"/g, '').toLowerCase()
			^^^^

SyntaxError: Unexpected identifier
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/share/unblockneteasemusic/core/src/hook.js:5:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by 1715173329** [comment]
已经修了，更新核心即可。
