### ISSUE TITLE
luci-app-unblockneteasemusic 无法启动，日志提示以下错误，有大佬知道什么意思吗？

### ISSUE THREAD

**Issue by michealhansun** [immortalwrt/luci-app-unblockneteasemusic#58]
/usr/share/unblockneteasemusic/core/src/app.js:59
const target = Array.from(hook.target.host)
                                      ^

TypeError: Cannot read property 'host' of undefined
    at Object.<anonymous> (/usr/share/unblockneteasemusic/core/src/app.js:59:39)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/share/unblockneteasemusic/core/app.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)

**Comment by 1715173329** [comment]
#57 #40

**Comment by michealhansun** [comment]
谢谢，删掉/usr/share/unblockneteasemusic 重新安装ok了
