### ISSUE TITLE
无法启动，使用的是releases里的v2.9版本

### ISSUE THREAD

**Issue by jiajiaxd** [immortalwrt/luci-app-unblockneteasemusic#66]
错误日志
`/usr/share/unblockneteasemusic/core/src/hook.js:409
		if (target == 0 || item.id == target) {
		^^

SyntaxError: Unexpected token 'if'
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/share/unblockneteasemusic/core/src/app.js:82:14)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
`

**Comment by msylgj** [comment]
@jiajiaxd already fixed. plz update the luci app

**Comment by ruitianchen** [comment]
请问解决了吗?

**Comment by zzz6839** [comment]
same issue with jiajiaxd, but im unable to update luci via update component>update Luci function，any idea except compiling the app?

![Capture](https://user-images.githubusercontent.com/57741549/129528432-c2b183d8-5134-4a90-b8ae-c928332e97fc.JPG)

**Comment by msylgj** [comment]
> same issue with jiajiaxd, but im unable to update luci via update component>update Luci function，any idea except compiling the app?
> 
> ![Capture](https://user-images.githubusercontent.com/57741549/129528432-c2b183d8-5134-4a90-b8ae-c928332e97fc.JPG)

the button "update luci" has been removed

replace js/lua files perhaps work
