### ISSUE TITLE
可以编译一版最新的ipk发布到releases吗？

### ISSUE THREAD

**Issue by jiajiaxd** [immortalwrt/luci-app-unblockneteasemusic#67]
可以编译一版最新的ipk发布到releases吗？
目前的release版本有严重BUG而不能使用
我自己编译出了一些问题

**Comment by EnnawYang** [comment]
[luci-app-unblockneteasemusic_2.9-3_all.ipk.zip](https://github.com/immortalwrt/luci-app-unblockneteasemusic/files/6990620/luci-app-unblockneteasemusic_2.9-3_all.ipk.zip)

**Comment by zzz6839** [comment]
这个版本的luci还是会出现一样的问题

/usr/share/unblockneteasemusic/core/src/hook.js:409
		if ((item.code != 200 || item.freeTrialInfo || item.br < 320000) && (target == 0 || item.id == target)) {
		^^

SyntaxError: Unexpected token 'if'
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/share/unblockneteasemusic/core/src/app.js:82:14)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)

**Comment by EnnawYang** [comment]
更新下主程序

**Comment by zzz6839** [comment]
是最新版本的主程序

**Comment by jiajiaxd** [comment]
我IPK装了也出问题 只有编译固件才行 如果有需要的话可以下载我自己构建的一个固件
https://github.com/jiajiaxd/openwrt_x86
@EnnawYang

**Comment by 1715173329** [comment]
https://github.com/immortalwrt/luci-app-unblockneteasemusic/releases/tag/v2.10-1

**Comment by zzz6839** [comment]
为什么我2.10版本还是一样的错误

/usr/share/unblockneteasemusic/core/src/hook.js:409
if ((item.code != 200 || item.freeTrialInfo || item.br < 320000) && (target == 0 || item.id == target)) {
^^

**Comment by zzz6839** [comment]
mini 1.2-9 版本我可以运行但是解锁只有部分的歌曲，寄了
