### ISSUE TITLE
最新版无法开启

### ISSUE THREAD

**Issue by Tianl0ng** [immortalwrt/luci-app-unblockneteasemusic#68]
报错日志：
/usr/share/unblockneteasemusic/core/src/hook.js:409
		if ((item.code != 200 || item.freeTrialInfo) && (target == 0 || item.id == target)) {
		^^

SyntaxError: Unexpected token 'if'
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/share/unblockneteasemusic/core/src/app.js:82:14)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)

点击更新提示已经是最新版

**Comment by h6fYe34KFSiH** [comment]
换 luci-app-unblockneteasemusic-mini 可以正常用

**Comment by jiajiaxd** [comment]
下载https://github.com/immortalwrt/luci-app-unblockneteasemusic/issues/67#issuecomment-899298894这里的
