### ISSUE TITLE
UnblockNeteaseMusic 未运行，日志报错

### ISSUE THREAD

**Issue by hot36952** [immortalwrt/luci-app-unblockneteasemusic#72]
R2S刷的是你的固件，最近几天网易云插件报错。

/usr/share/unblockneteasemusic/core/src/hook.js:409
		if (target == 0 || item.id == target) {
		^^

SyntaxError: Unexpected token 'if'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/share/unblockneteasemusic/core/src/app.js:82:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by 1715173329** [comment]
#71
