### ISSUE TITLE
启动后无法运行

### ISSUE THREAD

**Issue by bili-guigui** [immortalwrt/luci-app-unblockneteasemusic#76]
/usr/share/unblockneteasemusic/core/src/app.js:85
const target = Array.from(hook.target.host);
                                      ^

TypeError: Cannot read property 'host' of undefined
    at Object.<anonymous> (/usr/share/unblockneteasemusic/core/src/app.js:85:39)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/share/unblockneteasemusic/core/app.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)

**Comment by bili-guigui** [comment]
我看下hook.js 一打开是空的

**Comment by michealhansun** [comment]
Succeeded in updating core.
Current core version: 26ad320858e598dc1a70387c05503a412f9078d1.

/usr/share/unblockneteasemusic/core/src/app.js:85
const target = Array.from(hook.target.host);
                                      ^

TypeError: Cannot read property 'host' of undefined
    at Object.<anonymous> (/usr/share/unblockneteasemusic/core/src/app.js:85:39)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/share/unblockneteasemusic/core/app.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)

**Comment by EnnawYang** [comment]
@michealhansun

**Comment by bili-guigui** [comment]
> 我也是同样故障，修改hook.js 文件就可以运行了：
> 
> https://github.com/nondanee/UnblockNeteaseMusic/blob/master/src/hook.js

解决hook.js的问题后，又出现一个问题。。。
usage: unblockneteasemusic [-v] [-p port] [-a address] [-u url] [-f host]
                           [-o source [source ...]] [-t token] [-e url] [-s]
                           [-h]
unblockneteasemusic: error: extra arguments found: default

**Comment by zzz6839** [comment]
+1, 用的是2.10-2的ipk，无论是修改hook.js还是移除掉core再重装都有问题

**Comment by 1715173329** [comment]
Please upgrade to 2.10-2.

**Comment by zzz6839** [comment]
> > 我也是同样故障，修改hook.js 文件就可以运行了：
> > https://github.com/nondanee/UnblockNeteaseMusic/blob/master/src/hook.js
> 
> 解决hook.js的问题后，又出现一个问题。。。
> usage: unblockneteasemusic [-v] [-p port] [-a address] [-u url] [-f host]
> [-o source [source ...]] [-t token] [-e url] [-s]
> [-h]
> unblockneteasemusic: error: extra arguments found: default

把强制音源替换从默认修改为kuwo kugou，或者其他你想用的音源

**Comment by lxl6125** [comment]
> Please upgrade to 2.10-2.

更新了还是不行

**Comment by zzz6839** [comment]
> > Please upgrade to 2.10-2.
> 
> 更新了还是不行

把音源从默认换酷我，宝贝

**Comment by lxl6125** [comment]
> > > Please upgrade to 2.10-2.
> > 
> > 
> > 更新了还是不行
> 
> 把音源从默认换酷我，宝贝

也不行啊，宝贝
而且日志是空的
![2021-08-22_22-34](https://user-images.githubusercontent.com/21015800/130359054-07337577-a25e-42c3-8a01-46764cff0f83.png)
