### ISSUE TITLE
启用插件失败，报错日志如下

### ISSUE THREAD

**Issue by zlr1** [immortalwrt/luci-app-unblockneteasemusic#80]
Succeeded in updating core.
Current core version: 36ce09224942d3ea846bbb4182a7ab3318e73251.

/usr/share/unblockneteasemusic/core/src/app.js:85
const target = Array.from(hook.target.host);
                                      ^

TypeError: Cannot read property 'host' of undefined
    at Object.<anonymous> (/usr/share/unblockneteasemusic/core/src/app.js:85:39)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/share/unblockneteasemusic/core/app.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)

**Comment by 1715173329** [comment]
#71

**Comment by zlr1** [comment]
卸载核心和luci app 之后重心安装最新版本。只有更新主程序。没有更新核心的选项

**Comment by zlr1** [comment]
> 卸载核心和luci app 之后重心安装最新版本。只有更新主程序。没有更新核心的选项

已找到问题，点击更新提示最新版本。但内核没有更新。只需删除/usr/share/unblockneteasemusic/下的core_local_ver文件再点击更新即可解决
